# Generated by Django 5.2.1 on 2025-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmicevent',
            name='borough',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='changes_updates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='hosts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='last_verified',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='latest_end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='other_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='signup_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='sms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='stage_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openmicevent',
            name='venue_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
