# Generated by Django 5.2.1 on 2025-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mics', '0002_openmicevent_borough_openmicevent_changes_updates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openmicevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openmicevent',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
