# Generated by Django 5.2.1 on 2025-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mics', '0003_alter_openmicevent_date_alter_openmicevent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmicevent',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('verified tediously', 'Verified Tediously'), ('unverified', 'Unverified')], default='unverified', max_length=20),
        ),
    ]
