# Generated by Django 5.2.1 on 2025-05-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mics', '0004_openmicevent_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openmicevent',
            name='sms',
        ),
    ]
